### ISSUE TITLE
如果在data层 用SharePrefenerces存取数据。

### ISSUE THREAD

**Issue by Sum41forever** [crazysunj/CrazyDaily#1]
如题，那不是要从表现层开始传递 Context ==>domain ==>data 这种类似的行为多了以后一不注意容易造成内存泄露，而且domain如何化为java模块也是一个大问题。

**Comment by Sum41forever** [comment]
我的想法是涉及上下文的 操作都放在表现层的P中进行处理。
但是这样又破坏了数据来源的架构，理想状态，所有数据应该都从data ==》domain ==》app

**Comment by crazysunj** [comment]
你好，SharedPreferences确切来说是Android的东西，用来存储一些简单的东西，你非要把它当成一个重要的存储手段，又不破坏架构，你可以参考Repository。
