### ISSUE TITLE
DaggerActivityComponent找不到是什么原因？

### ISSUE THREAD

**Issue by kouhengsheng** [crazysunj/CrazyDaily#4]
错误: 找不到符号
符号:   类 DaggerActivityComponent
位置: 程序包 com.crazysunj.crazydaily.di.component

**Comment by crazysunj** [comment]
你好，这个是编译生成的，可以了解一下dagger2

**Comment by kouhengsheng** [comment]
我看你的config.gradle里有dagger的依赖，但是presentation的build.gradle里没有dagger的依赖啊，是不是因为这里面没有dagger的依赖造成的。

**Comment by crazysunj** [comment]
依赖在data模块
